#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../sass-graph@4.0.0/node_modules/sass-graph/bin/sassgraph" "$@"
else
  exec node  "$basedir/../../../../../sass-graph@4.0.0/node_modules/sass-graph/bin/sassgraph" "$@"
fi
