# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Packages CI

on:
  push:
    branches: [ "main" ]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.9.3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org/
        cache: "pnpm"
    # 设置 npm token
    - name: set npm token
      run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
    # 安装依赖
    - name: install dependencies
      run: pnpm install
    # 设置 git 配置信息
    - name: set git config
      run: git config --global user.email "qoxop@bricking.dev" && git config --global user.name "CI"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # 检查版本是否更新，更新则发包
    - name: Check and release packages
      run: pnpm run ci:publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
