# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Packages CI

on:
  push:
    branches: [ "main" ]
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org/
        cache: "pnpm"
    # 设置 npmrc
    - name: set npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
    # 设置 pnpm 缓存目录
    - name: setup pnpm config
      run: pnpm config set store-dir $PNPM_CACHE_FOLDER
    # 安装依赖
    - name: install dependencies
      run: pnpm install
    # 设置 git 配置信息
    - name: set git config
      run: git config --global user.email "qoxop@bricking.dev" && && git config --global user.name "CI"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # 检查版本是否更新，更新则发包
    - name: Check and release packages
      run: pnpm run ci:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
